[package]
name = "deno-argon2id"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
codegen-units = 1
strip = true
lto = true

[dependencies]
argon2 = { version = "0.4.1", features = ["alloc"] }
